// const something = new Promise((resolve, reject) => {

// });

// something.then(data => data).catch(err => console.log(err));